export const Config: any = {
  dataCacheEnabled: false,
  imageCacheEnabled: true,
  defaultRoute: '/welcome',
  apiUrl: 'https://dev.jammm.app/backend/api/v1',
  imageUrl: 'https://dev.jammm.app/backend',
  googleMapApiKey: 'AIzaSyCAEf0XHIfZFbXXLLANyLGi84RLqwKMKKM',
  googleGeocodeUrl: 'https://maps.googleapis.com/maps/api/geocode/json',
  facebookAuthClientId: '373201195846239',
  instagramAuthClientId: '684282327603640',
  googleAuth: {
    clientId: '811182156187-2p26v2vuqm3vop5iuikftv80fkea2huu.apps.googleusercontent.com',
    redirectUri: 'https://auth.expo.io/@david-fiaty/jam-native',
    //redirectUri: 'http://localhost:3000',
    authorizationEndpoint: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenEndpoint: 'https://oauth2.googleapis.com/token',
  },
  storageKey: '@jam',
  mainSection: 'jams',
  defaultLanguage: 'en',
  fallbackLanguage: 'en',
  appNamespace: 'jam-native',
  uiDateFormat: 'MMM Do YYYY HH:mm',
  dbDateFormat: 'YYYY-MM-DDTHH:mm:ssZ',
  logoImageSize: 512,
  paginationSize: 20,
  maxMapResults: 20,
  maxUserNameLength: 28,
  notificationUpdateInterval: 10000,
  messageDisplayDuration: 3500,
  searchDebounceDuration: 1000,
  defaultCountry: 'tg',
  allowedCountries: {
    phone: [],
    jam: ['bj', 'bf', 'gh', 'ci', 'ke', 'ng', 'sn', 'tg'],
  },
  defaultLocation: {
    latitude: 8.6195,
    longitude: 0.8248,
  },
  storageKeys: {
    currentLanguage: 'language',
    profileData: 'profileData',
    viewedNotifications: 'viewedNotifications',
    deletedJams: 'deletedJams',
  },
  forceLogin: {
    enabled: true,
    credentials: {
      email: 'mitsiomotu@yopmail.com',
      password: 'Password1234',
      //email: 'zomi3@yopmail.com',
      //password: 'Zomi3',
    },
  },
};