const Entities = [
  {
    name: 'jam',
    type: 'jams',
    fields: {
      id: 'id',
      category: 'type',
      description: 'caption',
      medias: 'medias',
      profile: 'profile',
      hosts: 'collaborators',
      jammers: 'jammers',
      comments: 'comments',
      sectors: 'sectors',
      location: 'location_type',
      scope: 'geographical_scope',
      countries: 'countries',
      latitude: 'geolocation_latitude',
      longitude: 'geolocation_longitude',
      active: 'is_active',
      deleted: 'is_deleted',
      period: 'period', 
      likes_count: 'likes_count',
      comments_count: 'comments_count',
    },
  },
  {
    name: 'media',
    type: 'medias',
    fields: {
      id: 'id',
      url: 'url',
    },
  },
  {
    name: 'sector',
    type: 'sectors',
    fields: {
      id: 'id',
      name: 'name',
      description: 'description',
    },
  },
  {
    name: 'period',
    type: 'periods',
    fields: {
      start: 'start_datetime',
      end: 'end_datetime',
    },
  },
  {
    name: 'country',
    type: 'countries',
    fields: {
      name: 'name',
      code: 'code',
    },
  },
  {
    name: 'personal',
    type: 'personals',
    fields: {
      id: 'id',
      first_name: 'first_name',
      last_name: 'last_name',
      experience: 'experience_in_field',
      creative_works: 'main_creative_works',
      other_works: 'other_creative_works',
    },
  },
  {
    name: 'organization',
    type: 'organizations',
    fields: {
      id: 'id',
      name: 'organization_name',
      created: 'creation_year',
      management: 'type_of_management',
      activities: 'organization_main_creative_activities',
      others: 'organization_other_creative_activities',
    },    
  },
  {
    name: 'picture',
    type: 'pictures',
    fields: {
      id: 'id',
      url: 'url',
    },
  },
  {
    name: 'comment',
    type: 'comments',
    fields: {
      id: 'id',
      profile: 'profile',
    },
  },

  {
    name: 'profile',
    type: 'profiles',
    fields: {
      id: 'id',
      name: 'profile_name',
      description: 'profile_description',
      picture: 'profile_picture',
      sectors: 'sectors',
      country: 'country',
      region: 'region',
      city: 'town_or_locality',
      latitude: 'geolocation_latitude',
      longitude: 'geolocation_longitude',
      type: 'profile_type',
      personal: 'profile_personal',
      organization: 'profile_organization',
      email: 'email',
      whatsapp: 'whatsapp_number',
      phone: 'phone_number',
      website: 'website_link',
      instagram: 'instagram_id',
      facebook: 'facebook_link',
      linkedin: 'linkedin_link',
      active: 'is_active',
      deleted: 'is_deleted',
    },
  },
  {
    name: 'host',
    type: 'hosts',
    fields: {
      id: 'id',
      name: 'profile_name',
      description: 'profile_description',
      picture: 'profile_picture',
      sectors: 'sectors',
      country: 'country',
      region: 'region',
      city: 'town_or_locality',
      latitude: 'geolocation_latitude',
      longitude: 'geolocation_longitude',
      type: 'profile_type',
      personal: 'profile_personal',
      organization: 'profile_organization',
      email: 'email',
      whatsapp: 'whatsapp_number',
      phone: 'phone_number',
      website: 'website_link',
      instagram: 'instagram_id',
      facebook: 'facebook_link',
      linkedin: 'linkedin_link',
      active: 'is_active',
      deleted: 'is_deleted',
    },
  },
  {
    name: 'jammer',
    type: 'jammers',
    fields: {
      id: 'id',
      name: 'profile_name',
      description: 'profile_description',
      picture: 'profile_picture',
      sectors: 'sectors',
      country: 'country',
      region: 'region',
      city: 'town_or_locality',
      latitude: 'geolocation_latitude',
      longitude: 'geolocation_longitude',
      type: 'profile_type',
      personal: 'profile_personal',
      organization: 'profile_organization',
      email: 'email',
      whatsapp: 'whatsapp_number',
      phone: 'phone_number',
      website: 'website_link',
      instagram: 'instagram_id',
      facebook: 'facebook_link',
      linkedin: 'linkedin_link',
      active: 'is_active',
      deleted: 'is_deleted',
    },
  },
];

export default Entities;