import JamsList from "@/components/list/JamsList";

export const ModalConfig: any = [
  {
    name: 'JamsList', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: <JamsList />,
  },
  {
    name: 'JamsMapView', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'JamForm', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'AddProjectForm', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'SelectJamsForm', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'ProfileForm', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'AddJamToProjectForm', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'SettingsMenu', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'NotificationsMenu', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'SearchView', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'LocationMapView', 
    effect: 'slide',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'JammersList', 
    effect: 'slide',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'CollaboratorsList', 
    effect: 'slide',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'SectorsList', 
    effect: 'slide',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'CountriesList', 
    effect: 'slide',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'HostsList', 
    effect: 'slide',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'SavedJamAction', 
    effect: 'slide',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'LikedJamAction', 
    effect: 'slide',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'AddedJamAction', 
    effect: 'slide',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'MoreJamActionsView', 
    effect: 'slide',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'JamScreen', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
  {
    name: 'ProjectScreen', 
    effect: 'fade',
    headerNavigation: true,
    footerNavigation: true,
    params: {},
    component: '',
  },
];
