export const Stack = [
  {
    name: 'JamsList', 
    effect: 'fade',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'MapView', 
    effect: 'fade',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'AddJamForm', 
    effect: 'fade',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'ProfileForm', 
    effect: 'fade',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'SettingsMenu', 
    effect: 'fade',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'NotificationsMenu', 
    effect: 'fade',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'SearchView', 
    effect: 'fade',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'JammersList', 
    effect: 'slide',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'HostsList', 
    effect: 'slide',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'SaveJamView', 
    effect: 'slide',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'ShareJamView', 
    effect: 'slide',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
  {
    name: 'MoreJamView', 
    effect: 'slide',
    active: false,
    headerNavigation: true,
    footerNavigation: true,
  },
];
